### ISSUE TITLE
Support/ignore !vault values in vars

### ISSUE THREAD

**Issue by EdificomSA** [carlmontanari/nornir_ansible#123]
I'm trying to use an inventory with vars set with vault encrypted value but I face an error with ruamel constructor

```
>>> nr = InitNornir(config_file=NORNIR_CONFIG_FILE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir/init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir/init_nornir.py", line 20, in load_inventory
    inv = inventory_plugin(**config.inventory.options).load()
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 511, in __init__
    self.hosts, self.groups, self.defaults = parse(hostsfile)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 431, in parse
    parser.parse()
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 110, in parse
    self.parse_group("defaults", self.original_data["all"])
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 105, in parse_group
    self.parse_group(children, cast(AnsibleGroupDataDict, children_data), parent=group)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 85, in parse_group
    vars_file_data = self.read_vars_file(
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/nornir_ansible/plugins/inventory/ansible.py", line 268, in read_vars_file
    return cast(Dict[str, Any], YAML.load(f))
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 131, in construct_document
    for _dummy in generator:
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 674, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 189, in construct_non_recursive_object
    data = constructor(self, node)
  File "/home/xxx/.cache/pypoetry/virtualenvs/automation-nRq0ZfWj-py3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 690, in construct_undefined
    raise ConstructorError(
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!vault'
```

Is there any way to bypass parsing these variables and show a warning of which variables are undefined because of it ?
Or even decrypt them but it will need ansible-vault and probably more coding ?

**Comment by carlmontanari** [comment]
not as far as im aware / not at present at least (in context of this plugin).

I think the most obvious/easiest solution would be to not pass any inventory file/dir that includes vault things to nornir inventory (esp if you are asking to bypass them anyway). failing that, prs welcome but would defo not want to add much to this it should stay pretty dumb and simple I think.

**Comment by EdificomSA** [comment]
I found a way using a ruamel constructor : https://stackoverflow.com/questions/73184857/ruamel-yaml-constructor-constructorerror-could-not-determine-a-constructor-for

**Comment by EdificomSA** [comment]
To complete my answer, automagically decrypting Vaulted password when initializing Nornir Inventory  :
```
from ansible.constants import DEFAULT_VAULT_ID_MATCH
from ansible.parsing.vault import VaultLib, VaultSecret
import ruamel.yaml

vault = VaultLib([(DEFAULT_VAULT_ID_MATCH, VaultSecret('vaultpass'.encode()))])

yaml = ruamel.yaml.YAML(typ='safe')
@yaml.register_class
class Vault:
    yaml_tag = '!vault'

    def __init__(self, s):
        self._s = s

    @classmethod
    def from_yaml(cls, constructor, node):
        return cls(vault.decrypt(node.value).decode())

    def __repr__(self):
        return repr(self._s)
```
