### ISSUE TITLE
Plugin Not Registered 

### ISSUE THREAD

**Issue by erichkuehn** [carlmontanari/nornir_ansible#63]
> Been trying to use the ansible inventory plugin. Always get this error. Not sure what I'm doing wrong. 

from nornir import InitNornir
nr = InitNornir(config_file='config.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/3.8.2/lib/python3.8/site-packages/nornir/init_nornir.py", line 64, in InitNornir
    inventory=load_inventory(config),
  File "3.8.2/lib/python3.8/site-packages/nornir/init_nornir.py", line 17, in load_inventory
    inventory_plugin = InventoryPluginRegister.get_plugin(config.inventory.plugin)
  File "3.8.2/lib/python3.8/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin
    raise PluginNotRegistered(f"plugin {name!r} is not registered")
nornir.core.exceptions.PluginNotRegistered: plugin 'nornir.plugins.inventory.ansible.AnsibleInventory' is not registered

cat config.yaml 
---
inventory:
    plugin: nornir.plugins.inventory.ansible.AnsibleInventory
    options:
        hostsfile: "inventory"

cat inventory
[all]
prd-tora
prd-torb
prd-spn8

**Comment by carlmontanari** [comment]
`AnsibleInventory` not the fully qualified name thing is *probably* the issue, [example](https://github.com/carlmontanari/nornir_ansible#basic-example)

**Comment by erichkuehn** [comment]
Thanks. That worked.
